-- EquipmentData_Special_ch6.lua
-- 特殊装备：第六章·两界村之影

return {
    -- 仙1橙过渡装备：固定属性，无特效。
    ch6_xuntian_helmet = {
        name = "巡天头",
        slot = "helmet",
        icon = "image/icon_ch6_xuntian_helmet_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_xuntian_guard",
        fixedSubStats = true,
        mainStat = { maxHp = 750 },
        subStats = {
            { stat = "def", name = "防御力", value = 32 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "巡天防御套部件，提供稳定防御与生命过渡属性。",
    },

    ch6_xuntian_boots = {
        name = "巡天履",
        slot = "boots",
        icon = "image/icon_ch6_xuntian_boots_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_xuntian_guard",
        fixedSubStats = true,
        mainStat = { speed = 0.40 },
        subStats = {
            { stat = "def", name = "防御力", value = 32 },
            { stat = "maxHp", name = "生命值", value = 160 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
        },
        desc = "巡天防御套部件，适合第六章前中段防御过渡。",
    },

    ch6_yingyou_ring = {
        name = "影游戒",
        slot = "ring1",
        icon = "image/icon_ch6_yingyou_ring_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_yingyou_assault",
        fixedSubStats = true,
        mainStat = { atk = 112 },
        subStats = {
            { stat = "critRate", name = "暴击率", value = 0.03 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "影游攻击套部件，提供稳定攻击与暴击过渡属性。",
    },

    ch6_yingyou_necklace = {
        name = "影游链",
        slot = "necklace",
        icon = "image/icon_ch6_yingyou_necklace_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_yingyou_assault",
        fixedSubStats = true,
        mainStat = { critRate = 0.40 },
        subStats = {
            { stat = "atk", name = "攻击力", value = 32 },
            { stat = "critDmg", name = "暴击伤害", value = 0.10 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "影游攻击套部件，适合第六章前中段攻击过渡。",
    },

    ch6_lieshan_shoulder = {
        name = "裂山肩",
        slot = "shoulder",
        icon = "image/icon_ch6_lieshan_shoulder_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_lieshan_vitality",
        fixedSubStats = true,
        mainStat = { def = 112 },
        subStats = {
            { stat = "maxHp", name = "生命值", value = 220 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "裂山生命套部件，提供稳定生命与防御过渡属性。",
    },

    ch6_lieshan_armor = {
        name = "裂山衣",
        slot = "armor",
        icon = "image/icon_ch6_lieshan_armor_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_lieshan_vitality",
        fixedSubStats = true,
        mainStat = { def = 150 },
        subStats = {
            { stat = "maxHp", name = "生命值", value = 260 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "裂山生命套部件，适合第六章前中段生命过渡。",
    },

    ch6_tianbing_belt = {
        name = "天兵战带",
        slot = "belt",
        icon = "image/icon_ch6_tianbing_belt_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_tianbing_battle",
        fixedSubStats = true,
        mainStat = { maxHp = 562 },
        subStats = {
            { stat = "killHeal", name = "击杀回血", value = 120 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
            { stat = "def", name = "防御力", value = 32 },
        },
        desc = "东西营天兵击杀回血套部件，提供稳定续航过渡属性。",
    },

    ch6_tianbing_weapon = {
        name = "天兵战刃",
        slot = "weapon",
        icon = "image/icon_ch6_tianbing_weapon_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_tianbing_battle",
        fixedSubStats = true,
        mainStat = { atk = 187 },
        subStats = {
            { stat = "killHeal", name = "击杀回血", value = 120 },
            { stat = "critRate", name = "暴击率", value = 0.03 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
        },
        desc = "东西营天兵击杀回血套部件，适合第六章前中段续航过渡。",
    },

    -- 仙1青散件：带固定灵性属性，不配置套装效果。
    ch6_zhenjie_helmet = {
        name = "镇界盔",
        slot = "helmet",
        icon = "image/icon_ch6_zhenjie_helmet_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { maxHp = 900 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 24 },
            { stat = "atk", name = "攻击力", value = 30 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        spiritStat = { stat = "wisdom", name = "悟性", value = 9 },
        desc = "镇界五散件之一，头盔属性较好，适合太虚。",
    },

    ch6_zhenjie_armor = {
        name = "镇界甲",
        slot = "armor",
        icon = "image/icon_ch6_zhenjie_armor_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { def = 180 },
        subStats = {
            { stat = "constitution", name = "根骨", value = 18 },
            { stat = "maxHp", name = "生命值", value = 180 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
        },
        spiritStat = { stat = "constitution", name = "根骨", value = 9 },
        desc = "镇界五散件之一，均衡防御，保留仙缘词条。",
    },

    ch6_zhenjie_shoulder = {
        name = "镇界肩",
        slot = "shoulder",
        icon = "image/icon_ch6_zhenjie_shoulder_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { def = 135 },
        subStats = {
            { stat = "physique", name = "体魄", value = 18 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        spiritStat = { stat = "physique", name = "体魄", value = 9 },
        desc = "镇界五散件之一，均衡承伤，保留仙缘词条。",
    },

    ch6_zhenjie_belt = {
        name = "镇界带",
        slot = "belt",
        icon = "image/icon_ch6_zhenjie_belt_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { maxHp = 675 },
        subStats = {
            { stat = "fortune", name = "福缘", value = 18 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
            { stat = "atk", name = "攻击力", value = 30 },
        },
        spiritStat = { stat = "fortune", name = "福缘", value = 9 },
        desc = "镇界五散件之一，均衡续航，保留仙缘词条。",
    },

    ch6_zhenjie_boots = {
        name = "镇界履",
        slot = "boots",
        icon = "image/icon_ch6_zhenjie_boots_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { speed = 0.45 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 18 },
            { stat = "def", name = "防御力", value = 30 },
            { stat = "maxHp", name = "生命值", value = 180 },
        },
        spiritStat = { stat = "wisdom", name = "悟性", value = 9 },
        desc = "镇界五散件之一，均衡机动，保留仙缘词条。",
    },

    -- 哼哈回生套：独立章节特殊套装，不进入制式套装池。
    ch6_heng_cyan_helmet = {
        name = "哼元帅战盔",
        slot = "helmet",
        icon = "image/icon_ch6_heng_cyan_helmet_20260701051150.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        setId = "ch6_hengha_regen",
        fixedSubStats = true,
        mainStat = { maxHp = 900 },
        subStats = {
            { stat = "physique", name = "体魄", value = 30 },
            { stat = "hpRegen", name = "生命回复", value = 6 },
            { stat = "critDmg", name = "暴击伤害", value = 0.10 },
        },
        spiritStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.01 },
        desc = "哼哈回生套部件，偏向镇岳承伤与生命回复。",
    },

    ch6_ha_cyan_armor = {
        name = "哈元帅战甲",
        slot = "armor",
        icon = "image/icon_ch6_ha_cyan_armor_20260701051150.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        setId = "ch6_hengha_regen",
        fixedSubStats = true,
        mainStat = { def = 180 },
        subStats = {
            { stat = "constitution", name = "根骨", value = 30 },
            { stat = "heavyHit", name = "重击值", value = 140 },
            { stat = "critRate", name = "暴击率", value = 0.03 },
        },
        spiritStat = { stat = "tianzhuDamage", name = "天诛伤害", value = 0.05 },
        desc = "哼哈回生套部件，偏向罗汉承伤与重击。",
    },

    -- 仙1红特殊装备：按文档指定特效/额外属性固定落表。
    ch6_toad_immortal_boots = {
        name = "蛤蟆仙履",
        slot = "boots",
        icon = "image/icon_ch6_toad_immortal_boots_20260701051033.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { speed = 0.50 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.12 },
            { stat = "atk", name = "攻击力", value = 36 },
            { stat = "maxHp", name = "生命值", value = 220 },
        },
        spiritStat = { stat = "fortune", name = "福缘", value = 11.5 },
        specialEffect = {
            type = "evade_damage",
            name = "蛤蟆仙步",
            evadeChance = 0.10,
        },
        desc = "与踏云履一致，10%概率完全闪避一次伤害。",
    },

    ch6_heng_weapon = {
        name = "哼大刀",
        slot = "weapon",
        icon = "image/icon_ch6_heng_weapon_20260701051033.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.396 },
            { stat = "hpRegen", name = "生命回复", value = 9 },
            { stat = "fortune", name = "福缘", value = 23 },
        },
        spiritStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.01 },
        desc = "哼元帅红武器，本体无特效，可作为后续合成仙1特效红武器的材料。",
    },

    ch6_ha_weapon = {
        name = "哈大刀",
        slot = "weapon",
        icon = "image/icon_ch6_ha_weapon_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critRate", name = "暴击率", value = 0.0792 },
            { stat = "killHeal", name = "击杀回血", value = 54 },
            { stat = "fortune", name = "福缘", value = 23 },
        },
        spiritStat = { stat = "tianzhuDamage", name = "天诛伤害", value = 0.05 },
        desc = "哈元帅红武器，本体无特效，可作为后续合成仙1特效红武器的材料。",
    },

    ch6_gua_king_ring = {
        name = "呱鸣大王戒",
        slot = "ring2",
        icon = "image/icon_ch6_gua_king_ring_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 157.5 },
        subStats = {
            { stat = "def", name = "防御力", value = 21.6 },
            { stat = "maxHp", name = "生命值", value = 108 },
            { stat = "hpRegen", name = "生命回复", value = 9 },
        },
        specialEffect = {
            type = "xianyuan_lowest_boost",
            name = "仙缘均衡",
            desc = "当前总值最低的仙缘属性额外获得100点加成（唯一，同类取最高值）",
            bonus = 100,
        },
        desc = "对标均灵环的仙1红戒，提供仙缘均衡特效。",
    },

    ch6_xianzun_1_ring = {
        name = "仙尊壹戒",
        slot = "ring1",
        icon = "image/icon_ch6_xianzun_1_ring_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 157.5 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 23 },
            { stat = "constitution", name = "根骨", value = 23 },
            { stat = "physique", name = "体魄", value = 23 },
        },
        saintStat = { stat = "fortune", name = "福缘", value = 23, confirmed = true },
        desc = "对标帝尊圣戒的仙1红戒，带固定圣性福缘。",
    },

    ch6_shixuan_demon_cape = {
        name = "蚀玄魔君氅",
        slot = "cape",
        icon = "image/icon_ch6_shixuan_demon_cape_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { dmgReduce = 0.378 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.396 },
            { stat = "maxHp", name = "生命值", value = 108 },
            { stat = "def", name = "防御力", value = 21.6 },
        },
        saintStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.02, confirmed = true },
        desc = "魔君红披风材料件，本体无特效，带固定圣性天诛概率。",
    },

    -- ===================== 第六章影炉打造（仙1终局装备） =====================

    ch6_true_zhuxian = {
        name = "真·诛仙",
        desc = "诛仙古剑经影炉二次解封，剑意不改，圣威更盛。",
        slot = "weapon",
        icon = "image/icon_fengyin_zhuxian_ch5_20260518083648.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.4455 },
            { stat = "critDmg", name = "暴击伤害", value = 0.4455 },
            { stat = "atk", name = "攻击力", value = 30.375 },
        },
        specialEffect = {
            type = "zhuxian",
            name = "诛仙·圣威",
            desc = "暴击时，追加一次15%攻击力的伤害（可暴击）",
            damagePercent = 0.15,
            canCrit = true,
            cooldown = 1.0,
        },
    },

    ch6_true_xianxian = {
        name = "真·陷仙",
        desc = "陷仙古剑经影炉二次解封，攻守两相依旧，圣威更盛。",
        slot = "weapon",
        icon = "image/icon_fengyin_xianxian_ch5_20260518085543.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "physique", name = "体魄", value = 23 },
            { stat = "maxHp", name = "生命值", value = 121.5 },
            { stat = "critRate", name = "暴击率", value = 0.0891 },
        },
        specialEffect = {
            type = "xianxian",
            name = "陷仙·圣威",
            desc = "生命>50%时暴击伤害+50%；生命≤50%时每秒恢复2%最大生命",
            highHpThreshold = 0.50,
            critDmgBonus = 0.50,
            lowHpRegenPercent = 0.02,
        },
    },

    ch6_true_luxian = {
        name = "真·戮仙",
        desc = "戮仙古剑经影炉二次解封，连斩之势不改，圣威更盛。",
        slot = "weapon",
        icon = "image/icon_fengyin_luxian_ch5_20260518083709.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "constitution", name = "根骨", value = 23 },
            { stat = "heavyHit", name = "重击伤害", value = 144 },
            { stat = "atk", name = "攻击力", value = 30.375 },
        },
        specialEffect = {
            type = "luxian",
            name = "戮仙·圣威",
            desc = "普攻时有10%概率发动连击，连击可触发普攻特效",
            procChance = 0.10,
            cooldown = 1.0,
        },
    },

    ch6_true_juexian = {
        name = "真·绝仙",
        desc = "绝仙古剑经影炉二次解封，绝命锋芒不改，圣威更盛。",
        slot = "weapon",
        icon = "image/icon_fengyin_juexian_ch5_20260518083649.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "killHeal", name = "击杀回血", value = 60.75 },
            { stat = "atk", name = "攻击力", value = 30.375 },
            { stat = "atk", name = "攻击力", value = 30.375 },
        },
        specialEffect = {
            type = "juexian",
            name = "绝仙·圣威",
            desc = "每次攻击获得1层绝命，每层攻击+3%，最多5层，持续4秒",
            stackPercent = 0.03,
            maxStacks = 5,
            duration = 4.0,
        },
    },

    ch6_zhenjie_saint_armor = {
        name = "镇界仙甲",
        desc = "镇界五甲归一，受创后可展开不覆盖其他护盾的镇界天幕。",
        slot = "armor",
        icon = "image/icon_ch6_zhenjie_saint_armor_20260711023224.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { def = 210 },
        subStats = {
            { stat = "physique", name = "体魄", value = 23 },
            { stat = "maxHp", name = "生命值", value = 121.5 },
            { stat = "critDmg", name = "暴击伤害", value = 0.4455 },
        },
        specialEffect = {
            type = "zhenjie_shield",
            name = "镇界天幕",
            desc = "受到生命伤害后，若镇界护盾不存在，则有20%概率获得总防御×3的独立护盾，持续6秒，冷却15秒",
            triggerChance = 0.20,
            defMultiplier = 3,
            duration = 6,
            cooldown = 15,
        },
    },

    ch6_hengha_dual_blade = {
        name = "哼哈双刃",
        desc = "哼哈二刃合铸，震杀之力在当前仙阶足以重创强敌。",
        slot = "weapon",
        icon = "image/icon_ch6_hengha_dual_blade_20260711023224.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critRate", name = "暴击率", value = 0.0891 },
            { stat = "critDmg", name = "暴击伤害", value = 0.4455 },
            { stat = "wisdom", name = "悟性", value = 23 },
        },
        specialEffect = {
            type = "hengha_fixed_burst",
            name = "哼哈震杀",
            desc = "普攻15%概率追加50000点固定伤害，不可暴击，冷却1秒",
            procChance = 0.15,
            fixedDamage = 50000,
            cooldown = 1.0,
        },
    },

    ch6_guagua_junling_ring = {
        name = "呱呱均灵环",
        desc = "呱鸣大王戒与均灵环合铸，均衡最低仙缘，并附带一条随机圣性。",
        slot = "ring2",
        icon = "image/icon_ch6_guagua_junling_ring_20260711023224.png",
        quality = "gold",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        mainStat = { atk = 187.5 },
        subStats = {
            { stat = "def", name = "防御力", value = 25.2 },
            { stat = "maxHp", name = "生命值", value = 126 },
            { stat = "hpRegen", name = "生命回复", value = 10.5 },
        },
        specialEffect = {
            type = "xianyuan_lowest_boost",
            name = "呱呱均灵",
            desc = "当前总值最低的仙缘属性额外获得150点加成（唯一，同类取最高值）",
            bonus = 150,
        },
    },

    ch6_shijie_saint_cape = {
        name = "蚀界仙氅",
        desc = "深渊圣氅与蚀玄魔君氅合铸，渊甲护身之力完整延续。",
        slot = "cape",
        icon = "image/icon_ch6_shijie_saint_cape_20260711023224.png",
        quality = "gold",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        hasSaintStat = true,
        -- T11 金色仙器：0.02 × PCT_T11(9.0) × gold(2.5) = 0.45
        mainStat = { dmgReduce = 0.45 },
        subStats = {
            -- T11 金色仙器模板中值：实际打造按金色 1.2~1.6 区间随机。
            { stat = "def", name = "防御力", value = 25.2 },
            { stat = "critDmg", name = "暴击伤害", value = 0.462 },
            { stat = "wisdom", name = "悟性", value = 27 },
        },
        specialEffect = {
            type = "yuanjia",
            name = "渊甲护身",
            desc = "受到伤害后，若当前生命低于50%，获得12%减伤，持续4秒，冷却8秒",
            lowHpThreshold = 0.50,
            dmgReduce = 0.12,
            duration = 4,
            cooldown = 8,
        },
    },
}
