-- EquipmentData_Special_ch6.lua
-- 特殊装备：第六章·两界村之影

return {
    -- 仙1橙过渡装备：固定属性，无特效。
    ch6_xuntian_helmet = {
        name = "巡天头",
        slot = "helmet",
        icon = "image/icon_ch6_xuntian_helmet_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_xuntian_guard",
        fixedSubStats = true,
        mainStat = { maxHp = 750 },
        subStats = {
            { stat = "def", name = "防御力", value = 32 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "巡天防御套部件，提供稳定防御与生命过渡属性。",
    },

    ch6_xuntian_boots = {
        name = "巡天履",
        slot = "boots",
        icon = "image/icon_ch6_xuntian_boots_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_xuntian_guard",
        fixedSubStats = true,
        mainStat = { speed = 0.40 },
        subStats = {
            { stat = "def", name = "防御力", value = 32 },
            { stat = "maxHp", name = "生命值", value = 160 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
        },
        desc = "巡天防御套部件，适合第六章前中段防御过渡。",
    },

    ch6_yingyou_ring = {
        name = "影游戒",
        slot = "ring1",
        icon = "image/icon_ch6_yingyou_ring_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_yingyou_assault",
        fixedSubStats = true,
        mainStat = { atk = 112 },
        subStats = {
            { stat = "critRate", name = "暴击率", value = 0.03 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "影游攻击套部件，提供稳定攻击与暴击过渡属性。",
    },

    ch6_yingyou_necklace = {
        name = "影游链",
        slot = "necklace",
        icon = "image/icon_ch6_yingyou_necklace_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_yingyou_assault",
        fixedSubStats = true,
        mainStat = { critRate = 0.40 },
        subStats = {
            { stat = "atk", name = "攻击力", value = 32 },
            { stat = "critDmg", name = "暴击伤害", value = 0.10 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "影游攻击套部件，适合第六章前中段攻击过渡。",
    },

    ch6_lieshan_shoulder = {
        name = "裂山肩",
        slot = "shoulder",
        icon = "image/icon_ch6_lieshan_shoulder_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_lieshan_vitality",
        fixedSubStats = true,
        mainStat = { def = 112 },
        subStats = {
            { stat = "maxHp", name = "生命值", value = 220 },
            { stat = "hpRegen", name = "生命回复", value = 1 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "裂山生命套部件，提供稳定生命与防御过渡属性。",
    },

    ch6_lieshan_armor = {
        name = "裂山衣",
        slot = "armor",
        icon = "image/icon_ch6_lieshan_armor_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_lieshan_vitality",
        fixedSubStats = true,
        mainStat = { def = 150 },
        subStats = {
            { stat = "maxHp", name = "生命值", value = 260 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        desc = "裂山生命套部件，适合第六章前中段生命过渡。",
    },

    ch6_tianbing_belt = {
        name = "天兵战带",
        slot = "belt",
        icon = "image/icon_ch6_tianbing_belt_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_tianbing_battle",
        fixedSubStats = true,
        mainStat = { maxHp = 562 },
        subStats = {
            { stat = "killHeal", name = "击杀回血", value = 120 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
            { stat = "def", name = "防御力", value = 32 },
        },
        desc = "东西营天兵击杀回血套部件，提供稳定续航过渡属性。",
    },

    ch6_tianbing_weapon = {
        name = "天兵战刃",
        slot = "weapon",
        icon = "image/icon_ch6_tianbing_weapon_20260701044037.png",
        quality = "orange",
        tier = 11,
        sellPrice = 2500,
        setId = "ch6_tianbing_battle",
        fixedSubStats = true,
        mainStat = { atk = 187 },
        subStats = {
            { stat = "killHeal", name = "击杀回血", value = 120 },
            { stat = "critRate", name = "暴击率", value = 0.03 },
            { stat = "critDmg", name = "暴击伤害", value = 0.08 },
        },
        desc = "东西营天兵击杀回血套部件，适合第六章前中段续航过渡。",
    },

    -- 仙1青散件：带固定灵性属性，不配置套装效果。
    ch6_zhenjie_helmet = {
        name = "镇界盔",
        slot = "helmet",
        icon = "image/icon_ch6_zhenjie_helmet_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { maxHp = 900 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 24 },
            { stat = "atk", name = "攻击力", value = 30 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        spiritStat = { stat = "wisdom", name = "悟性", value = 9 },
        desc = "镇界五散件之一，头盔属性较好，适合太虚。",
    },

    ch6_zhenjie_armor = {
        name = "镇界甲",
        slot = "armor",
        icon = "image/icon_ch6_zhenjie_armor_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { def = 180 },
        subStats = {
            { stat = "constitution", name = "根骨", value = 18 },
            { stat = "maxHp", name = "生命值", value = 180 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
        },
        spiritStat = { stat = "constitution", name = "根骨", value = 9 },
        desc = "镇界五散件之一，均衡防御，保留仙缘词条。",
    },

    ch6_zhenjie_shoulder = {
        name = "镇界肩",
        slot = "shoulder",
        icon = "image/icon_ch6_zhenjie_shoulder_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { def = 135 },
        subStats = {
            { stat = "physique", name = "体魄", value = 18 },
            { stat = "hpRegen", name = "生命回复", value = 2 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
        },
        spiritStat = { stat = "physique", name = "体魄", value = 9 },
        desc = "镇界五散件之一，均衡承伤，保留仙缘词条。",
    },

    ch6_zhenjie_belt = {
        name = "镇界带",
        slot = "belt",
        icon = "image/icon_ch6_zhenjie_belt_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { maxHp = 675 },
        subStats = {
            { stat = "fortune", name = "福缘", value = 18 },
            { stat = "killHeal", name = "击杀回血", value = 90 },
            { stat = "atk", name = "攻击力", value = 30 },
        },
        spiritStat = { stat = "fortune", name = "福缘", value = 9 },
        desc = "镇界五散件之一，均衡续航，保留仙缘词条。",
    },

    ch6_zhenjie_boots = {
        name = "镇界履",
        slot = "boots",
        icon = "image/icon_ch6_zhenjie_boots_20260701051033.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { speed = 0.45 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 18 },
            { stat = "def", name = "防御力", value = 30 },
            { stat = "maxHp", name = "生命值", value = 180 },
        },
        spiritStat = { stat = "wisdom", name = "悟性", value = 9 },
        desc = "镇界五散件之一，均衡机动，保留仙缘词条。",
    },

    -- 哼哈回生套：独立章节特殊套装，不进入制式套装池。
    ch6_heng_cyan_helmet = {
        name = "哼元帅战盔",
        slot = "helmet",
        icon = "image/icon_ch6_heng_cyan_helmet_20260701051150.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        setId = "ch6_hengha_regen",
        fixedSubStats = true,
        mainStat = { maxHp = 900 },
        subStats = {
            { stat = "physique", name = "体魄", value = 30 },
            { stat = "hpRegen", name = "生命回复", value = 6 },
            { stat = "critDmg", name = "暴击伤害", value = 0.10 },
        },
        spiritStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.01 },
        desc = "哼哈回生套部件，偏向镇岳承伤与生命回复。",
    },

    ch6_ha_cyan_armor = {
        name = "哈元帅战甲",
        slot = "armor",
        icon = "image/icon_ch6_ha_cyan_armor_20260701051150.png",
        quality = "cyan",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        setId = "ch6_hengha_regen",
        fixedSubStats = true,
        mainStat = { def = 180 },
        subStats = {
            { stat = "constitution", name = "根骨", value = 30 },
            { stat = "heavyHit", name = "重击值", value = 140 },
            { stat = "critRate", name = "暴击率", value = 0.03 },
        },
        spiritStat = { stat = "tianzhuDamage", name = "天诛伤害", value = 0.05 },
        desc = "哼哈回生套部件，偏向罗汉承伤与重击。",
    },

    -- 仙1红特殊装备：按文档指定特效/额外属性固定落表。
    ch6_toad_immortal_boots = {
        name = "蛤蟆仙履",
        slot = "boots",
        icon = "image/icon_ch6_toad_immortal_boots_20260701051033.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { speed = 0.50 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.12 },
            { stat = "atk", name = "攻击力", value = 36 },
            { stat = "maxHp", name = "生命值", value = 220 },
        },
        spiritStat = { stat = "fortune", name = "福缘", value = 11.5 },
        specialEffect = {
            type = "evade_damage",
            name = "蛤蟆仙步",
            evadeChance = 0.10,
        },
        desc = "与踏云履一致，10%概率完全闪避一次伤害。",
    },

    ch6_heng_weapon = {
        name = "哼大刀",
        slot = "weapon",
        icon = "image/icon_ch6_heng_weapon_20260701051033.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.396 },
            { stat = "hpRegen", name = "生命回复", value = 9 },
            { stat = "fortune", name = "福缘", value = 23 },
        },
        spiritStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.01 },
        desc = "哼元帅红武器，本体无特效，可作为后续合成仙1特效红武器的材料。",
    },

    ch6_ha_weapon = {
        name = "哈大刀",
        slot = "weapon",
        icon = "image/icon_ch6_ha_weapon_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 262.5 },
        subStats = {
            { stat = "critRate", name = "暴击率", value = 0.0792 },
            { stat = "killHeal", name = "击杀回血", value = 54 },
            { stat = "fortune", name = "福缘", value = 23 },
        },
        spiritStat = { stat = "tianzhuDamage", name = "天诛伤害", value = 0.05 },
        desc = "哈元帅红武器，本体无特效，可作为后续合成仙1特效红武器的材料。",
    },

    ch6_gua_king_ring = {
        name = "呱鸣大王戒",
        slot = "ring2",
        icon = "image/icon_ch6_gua_king_ring_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 157.5 },
        subStats = {
            { stat = "def", name = "防御力", value = 21.6 },
            { stat = "maxHp", name = "生命值", value = 108 },
            { stat = "hpRegen", name = "生命回复", value = 9 },
        },
        specialEffect = {
            type = "xianyuan_lowest_boost",
            name = "仙缘均衡",
            desc = "当前总值最低的仙缘属性额外获得100点加成（唯一）",
            bonus = 100,
        },
        desc = "对标均灵环的仙1红戒，提供仙缘均衡特效。",
    },

    ch6_xianzun_1_ring = {
        name = "仙尊壹戒",
        slot = "ring1",
        icon = "image/icon_ch6_xianzun_1_ring_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { atk = 157.5 },
        subStats = {
            { stat = "wisdom", name = "悟性", value = 23 },
            { stat = "constitution", name = "根骨", value = 23 },
            { stat = "physique", name = "体魄", value = 23 },
        },
        saintStat = { stat = "fortune", name = "福缘", value = 23, confirmed = true },
        desc = "对标帝尊圣戒的仙1红戒，带固定圣性福缘。",
    },

    ch6_shixuan_demon_cape = {
        name = "蚀玄魔君氅",
        slot = "cape",
        icon = "image/icon_ch6_shixuan_demon_cape_20260701051150.png",
        quality = "red",
        tier = 11,
        sellPrice = 7,
        sellCurrency = "lingYun",
        fixedSubStats = true,
        mainStat = { dmgReduce = 0.378 },
        subStats = {
            { stat = "critDmg", name = "暴击伤害", value = 0.396 },
            { stat = "maxHp", name = "生命值", value = 108 },
            { stat = "def", name = "防御力", value = 21.6 },
        },
        saintStat = { stat = "tianzhuChance", name = "天诛概率", value = 0.02, confirmed = true },
        desc = "魔君红披风材料件，本体无特效，带固定圣性天诛概率。",
    },
}
