-- ============================================================================
-- MonsterTypes_ch3_Reputation.lua - 声望体系挑战 R1-R8
-- 沈墨/陆青云/云裳/李无极 四组声望挑战
-- ============================================================================

---@param M table MonsterData 主模块
return function(M)
-- ===================== 挑战副本：血煞盟·沈墨（新声望体系 R1-R8） =====================
-- 新体系所有 BOSS 均为 emperor_boss，与旧 t1-t8 共存（旧存档向后兼容）

-- 声望等级1: T3 筑基初期（单阶段，仅基础技能）
M.Types.challenge_shenmo_r1 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 25,
    realm = "zhuji_1",
    bodyColor = {140, 50, 50, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 1,
    skills = { "line_charge", "whirlwind" },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.015 },
}

-- 声望等级2: T4 筑基后期（3阶段，增加十字斩 + P2/P3）
M.Types.challenge_shenmo_r2 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 35,
    realm = "zhuji_3",
    bodyColor = {170, 35, 35, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.015 },
}

-- 声望等级3: T5 金丹中期
M.Types.challenge_shenmo_r3 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 45,
    realm = "jindan_2",
    bodyColor = {195, 25, 25, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.02 },
}

-- 声望等级4: T6 元婴初期（增加狂暴buff）
M.Types.challenge_shenmo_r4 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 55,
    realm = "yuanying_1",
    bodyColor = {210, 18, 18, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.02 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级5: T7 化神初期
M.Types.challenge_shenmo_r5 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 70,
    realm = "huashen_1",
    bodyColor = {225, 12, 12, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.02 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级6: T8 合体初期
M.Types.challenge_shenmo_r6 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 85,
    realm = "heti_1",
    bodyColor = {235, 8, 8, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.02 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级7: T9 大乘初期
M.Types.challenge_shenmo_r7 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 100,
    realm = "dacheng_1",
    bodyColor = {245, 5, 5, 255},
    clawColor = {200, 30, 30},
    skillTextColor = {255, 80, 60, 255},
    warningColorOverride = {180, 30, 30, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.02 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级8: T10 渡劫初期（3阶段，圣者Boss，血印强化）
M.Types.challenge_shenmo_r8 = {
    name = "沈墨",
    icon = "🗡️",
    portrait = "Textures/npc_xuesha_spy.png",
    zone = "challenge_arena",
    category = "saint_boss",
    race = "human",
    level = 120,
    realm = "dujie_1",
    bodyColor = {255, 0, 0, 255},
    clawColor = {220, 20, 20},
    skillTextColor = {255, 60, 40, 255},
    warningColorOverride = {200, 20, 20, 140},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.4, intervalMult = 0.6,
          announce = "血海...翻涌吧！",
          triggerSkill = "shenmo_blood_flood",
          addSkill = "shenmo_shadow_clone" },
        { threshold = 0.25, atkMult = 2.5, speedMult = 1.6, intervalMult = 0.35,
          announce = "以我之血，染尽苍穹！",
          triggerSkill = "shenmo_blood_flood" },
    },
    dropTable = {},
    isChallenge = true,
    bloodMark = { damagePercent = 0.03 },
    berserkBuff = { atkSpeedMult = 1.4, speedMult = 1.4, cdrMult = 0.6 },
}

-- ═══════════════════════════════════════════════════════════════════
-- 浩气宗声望 BOSS：陆青云 R1-R8
-- 核心机制：正气结界（barrierZone）—— 周期性生成屏障区域
-- ═══════════════════════════════════════════════════════════════════

-- 声望等级1: T3 筑基初期（1阶段，基础技能）
M.Types.challenge_luqingyun_r1 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 25,
    realm = "zhuji_1",
    bodyColor = {50, 90, 160, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 1,
    skills = { "shield_bash", "rect_sweep" },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 30, maxCount = 2, damagePercent = 0.30, radius = 0.8 },
}

-- 声望等级2: T4 筑基后期（3阶段，增加 ground_pound + P2/P3）
M.Types.challenge_luqingyun_r2 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 35,
    realm = "zhuji_3",
    bodyColor = {45, 100, 180, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 28, maxCount = 2, damagePercent = 0.30, radius = 0.8 },
}

-- 声望等级3: T5 金丹中期
M.Types.challenge_luqingyun_r3 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 45,
    realm = "jindan_2",
    bodyColor = {40, 110, 200, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 25, maxCount = 3, damagePercent = 0.35, radius = 0.8 },
}

-- 声望等级4: T6 元婴初期（增加狂暴buff）
M.Types.challenge_luqingyun_r4 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 55,
    realm = "yuanying_1",
    bodyColor = {35, 120, 215, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 22, maxCount = 3, damagePercent = 0.35, radius = 0.8 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级5: T7 化神初期
M.Types.challenge_luqingyun_r5 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 70,
    realm = "huashen_1",
    bodyColor = {30, 130, 230, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 20, maxCount = 3, damagePercent = 0.35, radius = 0.8 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级6: T8 合体初期
M.Types.challenge_luqingyun_r6 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 85,
    realm = "heti_1",
    bodyColor = {25, 140, 240, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 18, maxCount = 4, damagePercent = 0.40, radius = 0.8 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级7: T9 大乘初期
M.Types.challenge_luqingyun_r7 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 100,
    realm = "dacheng_1",
    bodyColor = {20, 150, 250, 255},
    clawColor = {220, 180, 40},
    skillTextColor = {255, 220, 60, 255},
    warningColorOverride = {60, 140, 220, 120},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 15, maxCount = 4, damagePercent = 0.40, radius = 0.8 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级8: T10 渡劫初期（3阶段，圣者Boss，结界强化）
M.Types.challenge_luqingyun_r8 = {
    name = "陆青云",
    icon = "⚔️",
    portrait = "Textures/npc_haoqi_envoy.png",
    zone = "challenge_arena",
    category = "saint_boss",
    race = "human",
    level = 120,
    realm = "dujie_1",
    bodyColor = {30, 70, 200, 255},
    clawColor = {240, 200, 50},
    skillTextColor = {255, 230, 80, 255},
    warningColorOverride = {40, 120, 240, 140},
    phases = 3,
    skills = { "shield_bash", "rect_sweep", "ground_pound" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.4, intervalMult = 0.6,
          announce = "剑阵...起！",
          triggerSkill = "luqingyun_sword_array",
          addSkill = "luqingyun_prison" },
        { threshold = 0.25, atkMult = 2.5, speedMult = 1.6, intervalMult = 0.35,
          announce = "浩然正气，天地无极！",
          triggerSkill = "luqingyun_sword_array" },
    },
    dropTable = {},
    isChallenge = true,
    barrierZone = { interval = 12, maxCount = 5, damagePercent = 0.50, radius = 0.9 },
    berserkBuff = { atkSpeedMult = 1.4, speedMult = 1.4, cdrMult = 0.6 },
}

-- ═══════════════════════════════════════════════════════════════════
-- 青云门声望 BOSS：云裳 R1-R8
-- 核心机制：玉甲回响（jadeShield）—— 周期性激活护盾，反弹伤害+减伤
-- 玩家需要在护盾期间停止攻击，等护盾结束后加大输出
-- ═══════════════════════════════════════════════════════════════════

-- 声望等级1: T3 筑基初期（单阶段，仅基础技能）
M.Types.challenge_yunshang_r1 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 25,
    realm = "zhuji_1",
    bodyColor = {50, 160, 90, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 1,
    skills = { "jade_palm", "spirit_needle" },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 20, duration = 4.0, reflectPercent = 0.30, dmgReduction = 0.50 },
}

-- 声望等级2: T4 筑基后期（3阶段，增加云遁步 + P2/P3）
M.Types.challenge_yunshang_r2 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 35,
    realm = "zhuji_3",
    bodyColor = {45, 170, 100, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 19, duration = 4.0, reflectPercent = 0.30, dmgReduction = 0.50 },
}

-- 声望等级3: T5 金丹中期
M.Types.challenge_yunshang_r3 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 45,
    realm = "jindan_2",
    bodyColor = {40, 180, 110, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 17, duration = 4.5, reflectPercent = 0.35, dmgReduction = 0.55 },
}

-- 声望等级4: T6 元婴初期（增加狂暴buff）
M.Types.challenge_yunshang_r4 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 55,
    realm = "yuanying_1",
    bodyColor = {35, 190, 120, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 15, duration = 4.5, reflectPercent = 0.35, dmgReduction = 0.55 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级5: T7 化神初期
M.Types.challenge_yunshang_r5 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 70,
    realm = "huashen_1",
    bodyColor = {30, 200, 130, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 14, duration = 5.0, reflectPercent = 0.40, dmgReduction = 0.60 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级6: T8 合体初期
M.Types.challenge_yunshang_r6 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 85,
    realm = "heti_1",
    bodyColor = {25, 210, 140, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 13, duration = 5.0, reflectPercent = 0.45, dmgReduction = 0.65 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级7: T9 大乘初期
M.Types.challenge_yunshang_r7 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 100,
    realm = "dacheng_1",
    bodyColor = {20, 220, 150, 255},
    clawColor = {80, 200, 120},
    skillTextColor = {100, 240, 140, 255},
    warningColorOverride = {60, 180, 100, 120},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 12, duration = 5.5, reflectPercent = 0.50, dmgReduction = 0.70 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级8: T10 渡劫初期（3阶段，圣者Boss，玉甲强化）
M.Types.challenge_yunshang_r8 = {
    name = "云裳",
    icon = "🌿",
    portrait = "Textures/npc_qingyun_envoy.png",
    zone = "challenge_arena",
    category = "saint_boss",
    race = "human",
    level = 120,
    realm = "dujie_1",
    bodyColor = {30, 180, 80, 255},
    clawColor = {60, 220, 100},
    skillTextColor = {80, 255, 120, 255},
    warningColorOverride = {40, 200, 80, 140},
    phases = 3,
    skills = { "jade_palm", "spirit_needle", "cloud_drift" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.4, intervalMult = 0.6,
          announce = "你的攻势...还不够格！",
          triggerSkill = "yunshang_jade_storm",
          addSkill = "yunshang_root_armor" },
        { threshold = 0.25, atkMult = 2.5, speedMult = 1.6, intervalMult = 0.35,
          announce = "青云之道，岂容亵渎！",
          triggerSkill = "yunshang_jade_storm" },
    },
    dropTable = {},
    isChallenge = true,
    jadeShield = { interval = 10, duration = 6.0, reflectPercent = 0.60, dmgReduction = 0.80 },
    berserkBuff = { atkSpeedMult = 1.4, speedMult = 1.4, cdrMult = 0.6 },
}

-- ═══════════════════════════════════════════════════════════════════
-- 封魔殿声望 BOSS：凌战 R1-R8（封魔殿少帅，年轻一代）
-- 核心机制：封魔印（sealMark）—— 周期性叠加印记，满层爆发伤害
--   每隔 stackInterval 秒自动叠1层封魔印
--   达到 maxStacks 层时触发"封印爆发"，造成 burstDamagePercent × 玩家最大HP 的伤害
--   玩家每次攻击 BOSS 可削减 clearPerHit 层（鼓励持续输出）
-- ═══════════════════════════════════════════════════════════════════

-- 声望等级1: T3 筑基初期（1阶段，基础技能）
M.Types.challenge_liwuji_r1 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 25,
    realm = "zhuji_1",
    bodyColor = {120, 60, 160, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 1,
    skills = { "line_charge", "whirlwind" },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 5.0, maxStacks = 5, burstDamagePercent = 0.20, clearPerHit = 1 },
}

-- 声望等级2: T4 筑基后期（3阶段，增加十字斩 + P2/P3）
M.Types.challenge_liwuji_r2 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 35,
    realm = "zhuji_3",
    bodyColor = {130, 55, 170, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 4.5, maxStacks = 5, burstDamagePercent = 0.22, clearPerHit = 1 },
}

-- 声望等级3: T5 金丹中期
M.Types.challenge_liwuji_r3 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 45,
    realm = "jindan_2",
    bodyColor = {140, 50, 180, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 4.0, maxStacks = 5, burstDamagePercent = 0.25, clearPerHit = 1 },
}

-- 声望等级4: T6 元婴初期（加狂暴）
M.Types.challenge_liwuji_r4 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 55,
    realm = "yuanying_1",
    bodyColor = {150, 45, 190, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 3.5, maxStacks = 5, burstDamagePercent = 0.25, clearPerHit = 1 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级5: T7 化神初期
M.Types.challenge_liwuji_r5 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 70,
    realm = "huashen_1",
    bodyColor = {160, 40, 200, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 3.0, maxStacks = 5, burstDamagePercent = 0.25, clearPerHit = 1 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级6: T8 合体初期
M.Types.challenge_liwuji_r6 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 85,
    realm = "heti_1",
    bodyColor = {170, 35, 210, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 2.5, maxStacks = 5, burstDamagePercent = 0.25, clearPerHit = 1 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级7: T9 大乘初期
M.Types.challenge_liwuji_r7 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "emperor_boss",
    race = "human",
    level = 100,
    realm = "dacheng_1",
    bodyColor = {180, 30, 220, 255},
    clawColor = {180, 80, 220},
    skillTextColor = {200, 120, 255, 255},
    warningColorOverride = {140, 60, 180, 120},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.3, intervalMult = 0.7,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.0, speedMult = 1.5, intervalMult = 0.4,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 2.0, maxStacks = 5, burstDamagePercent = 0.25, clearPerHit = 1 },
    berserkBuff = { atkSpeedMult = 1.3, speedMult = 1.3, cdrMult = 0.7 },
}

-- 声望等级8: T10 渡劫初期（3阶段，圣者Boss，封印强化）
M.Types.challenge_liwuji_r8 = {
    name = "凌战",
    icon = "🔮",
    portrait = "Textures/npc_fengmo_envoy.png",
    zone = "challenge_arena",
    category = "saint_boss",
    race = "human",
    level = 120,
    realm = "dujie_1",
    bodyColor = {140, 40, 200, 255},
    clawColor = {200, 60, 240},
    skillTextColor = {220, 100, 255, 255},
    warningColorOverride = {160, 40, 200, 140},
    phases = 3,
    skills = { "line_charge", "whirlwind", "cross_smash" },
    phaseConfig = {
        { threshold = 0.6, speedMult = 1.4, intervalMult = 0.6,
          announce = "封魔之力...觉醒！",
          triggerSkill = "liwuji_seal_burst",
          addSkill = "liwuji_void_pull" },
        { threshold = 0.25, atkMult = 2.5, speedMult = 1.6, intervalMult = 0.35,
          announce = "万魔臣服，封印永镇！",
          triggerSkill = "liwuji_seal_burst" },
    },
    dropTable = {},
    isChallenge = true,
    sealMark = { stackInterval = 1.5, maxStacks = 6, burstDamagePercent = 0.30, clearPerHit = 1 },
    berserkBuff = { atkSpeedMult = 1.4, speedMult = 1.4, cdrMult = 0.6 },
}


end
